// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgLlUCel--oF5Rew87oo77Qdt06oOKck0',
    appId: '1:1065473302917:web:0323dd56f822ecea4f64ec',
    messagingSenderId: '1065473302917',
    projectId: 'teman-flutter-2',
    authDomain: 'teman-flutter-2.firebaseapp.com',
    storageBucket: 'teman-flutter-2.firebasestorage.app',
    measurementId: 'G-Y11JQTN0XL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjTCNI8oL2zBw1b4Dc1A5WlWOGDZX5yvU',
    appId: '1:1065473302917:android:6fbef37c281ac8904f64ec',
    messagingSenderId: '1065473302917',
    projectId: 'teman-flutter-2',
    storageBucket: 'teman-flutter-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-3DydQb377tNkqX_oGjFDRvhbjLRlH08',
    appId: '1:1065473302917:ios:c78cfff7dff278894f64ec',
    messagingSenderId: '1065473302917',
    projectId: 'teman-flutter-2',
    storageBucket: 'teman-flutter-2.firebasestorage.app',
    iosBundleId: 'com.example.temanFlutterAppCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgLlUCel--oF5Rew87oo77Qdt06oOKck0',
    appId: '1:1065473302917:web:0323dd56f822ecea4f64ec',
    messagingSenderId: '1065473302917',
    projectId: 'teman-flutter-2',
    authDomain: 'teman-flutter-2.firebaseapp.com',
    storageBucket: 'teman-flutter-2.firebasestorage.app',
    measurementId: 'G-Y11JQTN0XL',
  );
}
