// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkTJlG-4g35nZ4Tgf942MEd_bayGVOkSI',
    appId: '1:191190218355:web:feaf71c82dd882f3431c06',
    messagingSenderId: '191190218355',
    projectId: 'teman-flutter',
    authDomain: 'teman-flutter.firebaseapp.com',
    storageBucket: 'teman-flutter.firebasestorage.app',
    measurementId: 'G-84QKF92HQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG19soj7l2LRBsHWWpInTFpP9W8wdjDII',
    appId: '1:191190218355:android:0d4be9c1b516f797431c06',
    messagingSenderId: '191190218355',
    projectId: 'teman-flutter',
    storageBucket: 'teman-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaqEdyAKmdW2BUBdzXu0rkoeKhAU9npV4',
    appId: '1:191190218355:ios:9e4a7840a52e7f3a431c06',
    messagingSenderId: '191190218355',
    projectId: 'teman-flutter',
    storageBucket: 'teman-flutter.firebasestorage.app',
    iosBundleId: 'com.example.temanFlutterAppCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkTJlG-4g35nZ4Tgf942MEd_bayGVOkSI',
    appId: '1:191190218355:web:bcc294e60a3de129431c06',
    messagingSenderId: '191190218355',
    projectId: 'teman-flutter',
    authDomain: 'teman-flutter.firebaseapp.com',
    storageBucket: 'teman-flutter.firebasestorage.app',
    measurementId: 'G-3TWCEKNHB7',
  );
}
