import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../models/job_model.dart';
import '../services/firestore_service.dart';
import '../services/auth_service.dart';
class CreateJobScreen extends StatefulWidget {
  final Job? editingJob;

  const CreateJobScreen({super.key, this.editingJob});

  @override
  State<CreateJobScreen> createState() => _CreateJobScreenState();
}

class _CreateJobScreenState extends State<CreateJobScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _locationController = TextEditingController();
  final _salaryController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _requirementsController = TextEditingController();
  final _contactInfoController = TextEditingController();

  String _selectedJobType = 'Full-time';
  final List<String> _jobTypes = [
    'Full-time',
    'Part-time',
    'Internship',
    'Freelance',
    'Contract',
    'Others',
  ];

  bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    if (widget.editingJob != null) {
      _titleController.text = widget.editingJob!.title;
      _locationController.text = widget.editingJob!.location;
      _salaryController.text = widget.editingJob!.salary;
      _descriptionController.text = widget.editingJob!.description;
      _requirementsController.text = widget.editingJob!.requirements.join('\n');
      _contactInfoController.text = widget.editingJob!.contactInfo;
      if (_jobTypes.contains(widget.editingJob!.jobType)) {
        _selectedJobType = widget.editingJob!.jobType;
      }
    }
  }

  @override
  void dispose() {
    _titleController.dispose();
    _locationController.dispose();
    _salaryController.dispose();
    _descriptionController.dispose();
    _requirementsController.dispose();
    _contactInfoController.dispose();
    super.dispose();
  }

  Future<void> _submitJob() async {
    if (_formKey.currentState!.validate()) {
      setState(() {
        _isLoading = true;
      });

      try {
        final authService = Provider.of<AuthService>(context, listen: false);
        final user = authService.currentUser;

        final job = Job(
          id: '', // Generated by Firestore
          title: _titleController.text.trim(),
          location: _locationController.text.trim(),
          salary: _salaryController.text.trim(),
          jobType: _selectedJobType,
          description: _descriptionController.text.trim(),
          requirements: _requirementsController.text
              .split('\n')
              .where((s) => s.trim().isNotEmpty)
              .toList(),
          contactInfo: _contactInfoController.text.trim(),
          authorId: user?.uid ?? '',
          authorName: user?.displayName ?? 'Unknown',
          authorAvatar: user?.photoURL ?? '',
          postedDate: DateTime.now(),
        );

        if (widget.editingJob != null) {
          await Provider.of<FirestoreService>(
            context,
            listen: false,
          ).updateJob(widget.editingJob!.id, {
            'title': job.title,
            'location': job.location,
            'salary': job.salary,
            'jobType': job.jobType,
            'description': job.description,
            'requirements': job.requirements,
            'contactInfo': job.contactInfo,
          });
        } else {
          await Provider.of<FirestoreService>(
            context,
            listen: false,
          ).addJob(job);
        }

        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(
                widget.editingJob != null
                    ? 'Job updated successfully!'
                    : 'Job posted successfully!',
              ),
            ),
          );
          Navigator.pop(context);
        }
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(
            context,
          ).showSnackBar(SnackBar(content: Text('Error posting job: $e')));
        }
      } finally {
        if (mounted) {
          setState(() {
            _isLoading = false;
          });
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.editingJob != null ? 'Edit Job' : 'Post a Job'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              TextFormField(
                controller: _titleController,
                decoration: const InputDecoration(
                  labelText: 'Job Title',
                  border: OutlineInputBorder(),
                ),
                validator: (value) => value == null || value.isEmpty
                    ? 'Please enter a title'
                    : null,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _locationController,
                decoration: const InputDecoration(
                  labelText: 'Location',
                  border: OutlineInputBorder(),
                ),
                validator: (value) => value == null || value.isEmpty
                    ? 'Please enter location'
                    : null,
              ),
              const SizedBox(height: 16),
              DropdownButtonFormField<String>(
                initialValue: _selectedJobType,
                decoration: const InputDecoration(
                  labelText: 'Job Type',
                  border: OutlineInputBorder(),
                ),
                items: _jobTypes.map((type) {
                  return DropdownMenuItem(
                    value: type,
                    child: Text(type),
                  );
                }).toList(),
                onChanged: (value) {
                  if (value != null) {
                    setState(() {
                      _selectedJobType = value;
                    });
                  }
                },
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _salaryController,
                decoration: const InputDecoration(
                  labelText: 'Salary (e.g. 3.0M - 4.0M KRW)',
                  border: OutlineInputBorder(),
                ),
                validator: (value) => value == null || value.isEmpty
                    ? 'Please enter salary'
                    : null,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _descriptionController,
                decoration: const InputDecoration(
                  labelText: 'Job Description',
                  border: OutlineInputBorder(),
                ),
                maxLines: 5,
                validator: (value) => value == null || value.isEmpty
                    ? 'Please enter description'
                    : null,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _requirementsController,
                decoration: const InputDecoration(
                  labelText: 'Requirements (One per line)',
                  border: OutlineInputBorder(),
                ),
                maxLines: 3,
                validator: (value) => value == null || value.isEmpty
                    ? 'Please enter requirements'
                    : null,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _contactInfoController,
                decoration: const InputDecoration(
                  labelText: 'Contact Info (Email/Phone)',
                  border: OutlineInputBorder(),
                ),
                validator: (value) => value == null || value.isEmpty
                    ? 'Please enter contact info'
                    : null,
              ),
              const SizedBox(height: 24),
              ElevatedButton(
                onPressed: _isLoading ? null : _submitJob,
                style: ElevatedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(vertical: 16),
                  backgroundColor: Colors.teal,
                  foregroundColor: Colors.white,
                ),
                child: _isLoading
                    ? const CircularProgressIndicator(color: Colors.white)
                    : Text(
                        widget.editingJob != null ? 'Update Job' : 'Post Job',
                        style: const TextStyle(fontSize: 16),
                      ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
